package com.hotelnaylamp.view;

import com.hotelnaylamp.controller.ProductoController;
import com.hotelnaylamp.model.entities.Producto;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AñadirProductos extends javax.swing.JDialog {
    
    public AñadirProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblProducto = new javax.swing.JLabel();
        cboProductos = new javax.swing.JComboBox<>();
        lblCantidadProducto = new javax.swing.JLabel();
        spnCantidadProductos = new javax.swing.JSpinner();
        btnAgregarProducto = new javax.swing.JButton();
        scrContenedorTablaProductos = new javax.swing.JScrollPane();
        tblProductosSeleccionados = new javax.swing.JTable();
        lblPrecioTotal = new javax.swing.JLabel();
        txtPrecioTotal = new javax.swing.JTextField();
        btnConfirmarProductos = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio.setText("Precio:");

        txtPrecio.setColumns(3);

        lblProducto.setText("Producto:");

        cboProductos.setMaximumRowCount(15);

        lblCantidadProducto.setText("Cantidad:");

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        tblProductosSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrContenedorTablaProductos.setViewportView(tblProductosSeleccionados);

        lblPrecioTotal.setText("Precio Total:");

        txtPrecioTotal.setColumns(8);

        btnConfirmarProductos.setText("Confirmar");
        btnConfirmarProductos.addActionListener(this::btnConfirmarProductosActionPerformed);

        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.addActionListener(this::btnEliminarProductoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scrContenedorTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCantidadProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPrecioTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarProductos)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btnEliminarProducto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProducto)
                            .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadProducto)
                            .addComponent(spnCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scrContenedorTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarProductos))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        Producto seleccionado = (Producto) cboProductos.getSelectedItem();
        if(seleccionado == null) return;

        int cantidad = (int) spnCantidadProductos.getValue();
        if(cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
            return;
        }

        float precio = seleccionado.getPrecio();
        float subtotal = precio * cantidad;

        modeloTabla.addRow(new Object[]{
            seleccionado.getNombre(),
            cantidad,
            String.format("S/. %.2f", precio),
            String.format("S/. %.2f", subtotal)
        });

        totalProductos += subtotal;
        txtPrecioTotal.setText(String.format("S/. %.2f", totalProductos));

        // Resetear spinner
        spnCantidadProductos.setValue(1);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnConfirmarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarProductosActionPerformed
        dispose();
    }//GEN-LAST:event_btnConfirmarProductosActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        int filaSeleccionada = tblProductosSeleccionados.getSelectedRow();
        if(filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto para quitar");
            return;
        }

        // Restamos el subtotal del total
        String subtotalStr = modeloTabla.getValueAt(filaSeleccionada, 3)
                                        .toString().replace("S/. ", "");
        totalProductos -= Float.parseFloat(subtotalStr);
        txtPrecioTotal.setText(String.format("S/. %.2f", totalProductos));

        modeloTabla.removeRow(filaSeleccionada);
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnConfirmarProductos;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JComboBox<com.hotelnaylamp.model.entities.Producto> cboProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JScrollPane scrContenedorTablaProductos;
    private javax.swing.JSpinner spnCantidadProductos;
    private javax.swing.JTable tblProductosSeleccionados;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioTotal;
    // End of variables declaration//GEN-END:variables

    private ProductoController productoController = new ProductoController();
    private DefaultTableModel modeloTabla;
    private int habitacionAsignada;
    private float totalProductos = 0;

    public AñadirProductos(Window parent, boolean modal, int habitacionAsignada) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        initComponents();
        this.habitacionAsignada = habitacionAsignada;
        setTitle("Añadir Productos - Hab: " + habitacionAsignada);
        setLocationRelativeTo(parent);
        inicializarTabla();
        cargarProductosEnCombo();
        configurarEventos();
    }   
    
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel( new String[]{"Producto", "Cantidad", "Precio", "SubTotal"} , 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // ninguna celda editable
            }
        };
        tblProductosSeleccionados.setModel(modeloTabla);
    }

    private void cargarProductosEnCombo() {
        List<Producto> productos = productoController.cargarProductos();
        cboProductos.removeAllItems();
        for(Producto p : productos) {
            cboProductos.addItem(p);
        }
        // Mostrar precio del primero seleccionado
        if(!productos.isEmpty()) {
            txtPrecio.setText(
                String.valueOf(productos.get(0).getPrecio())
            );
        }
    }
    
    private void configurarEventos() {
        // Actualizar precio cuando cambia el producto
        cboProductos.addActionListener(e -> {
            Producto productoSeleccionado = (Producto) cboProductos.getSelectedItem();
            if(productoSeleccionado != null) {
                txtPrecio.setText(
                    String.valueOf(productoSeleccionado.getPrecio())
                );
            }
        });
    }
    
    public float getTotalProductos() {
        return totalProductos;
    }

    public List<Object[]> getProductosAgregados() {
        List<Object[]> productos = new ArrayList<>();
        for(int i = 0; i < modeloTabla.getRowCount(); i++) {
            productos.add(new Object[]{
                modeloTabla.getValueAt(i, 0), // nombre
                modeloTabla.getValueAt(i, 1), // cantidad
                modeloTabla.getValueAt(i, 2)  // precio
            });
        }
        return productos;
    }
}
