package com.hotelnaylamp.view;

import com.hotelnaylamp.controller.TrabajadorController;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JDialog {
    
    private TrabajadorController trabajadorController = new TrabajadorController();
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNaylamp = new javax.swing.JLabel();
        lblSGH = new javax.swing.JLabel();
        lblHotel = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNaylamp.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblNaylamp.setText("NAYLAMP");
        jPanel1.add(lblNaylamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblSGH.setText("Sistema de Gestion Hotelera");
        jPanel1.add(lblSGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lblHotel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblHotel.setText("HOTEL");
        jPanel1.add(lblHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_hotel_naylamp.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        lblUsuario.setText("USUARIO:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        txtUsuario.setColumns(15);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        lblContraseña.setText("CONTRASEÑA:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 100, 30));

        txtContraseña.setColumns(15);
        txtContraseña.setPreferredSize(new java.awt.Dimension(179, 24));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String contraseña = new String(txtContraseña.getPassword());
        String error = trabajadorController.validarLogin(txtUsuario.getText(), 
                                                        contraseña);
        if(error!=null){
            JOptionPane.showMessageDialog(this, error);
            return;
        }
        dispose(    );
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblHotel;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNaylamp;
    private javax.swing.JLabel lblSGH;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    
    public void inicializarLogin(){
        setTitle("Inicio de Sesion HNS");
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }



}
