package com.hotelnaylamp.view;

import com.hotelnaylamp.controller.HabitacionController;
import com.hotelnaylamp.controller.ReservaController;
import com.hotelnaylamp.model.entities.Habitacion;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;


public class MenuPrincipal extends javax.swing.JFrame {
    private ImageIcon iconLibre = new ImageIcon(getClass().getResource("/images/puerta_abierta.png"));
    private ImageIcon iconOcupado = new ImageIcon(getClass().getResource("/images/puerta_cerrada.png"));
    private ImageIcon iconReservado; //TODO: agregar imagen cuando se implemente
    private List<JToggleButton> listaBotones;
    private RegistroCliente ventanaRegistro = null;
    private HabitacionController habitacionController = new HabitacionController();
    private ReservaController reservaController = new ReservaController();

    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        listaBotones = new ArrayList<>();
        Component[] componentes = pnlHabitaciones.getComponents();
        for(Component comp : componentes) {
            if(comp instanceof JToggleButton) {
                listaBotones.add((JToggleButton) comp);
            }   
        }
        actualizarHabitaciones();
        for(JToggleButton boton : listaBotones) {
            boton.addActionListener(new ActionListener() { 
               @Override
               public void actionPerformed(ActionEvent evt) {
                   clickBoton(evt);
               }
            });
        }
    }

    
 
    
    private void actualizarHabitaciones() {
        List<Habitacion> habitaciones = habitacionController.obtenerTodasLasHabitaciones();

        for(int i = 0; i < habitaciones.size(); i++) {
            Habitacion habitacion = habitaciones.get(i);
            JToggleButton boton = listaBotones.get(i);

            if(habitacion.getEstado().equalsIgnoreCase("DISPONIBLE")) {
                boton.setIcon(iconLibre);
            } else if(habitacion.getEstado().equalsIgnoreCase("OCUPADO")) {
                boton.setIcon(iconOcupado);
            } else if(habitacion.getEstado().equalsIgnoreCase("RESERVADO")) {
                boton.setIcon(iconReservado);
            }

            boton.putClientProperty("Habitacion", habitacion.getNumero());
        }
    }
    
    
    private void clickBoton(ActionEvent evt) {
        JToggleButton boton = (JToggleButton) evt.getSource();
        String numeroHabitacion = boton.getClientProperty("Habitacion").toString();
        int ancho = (int) (pnlAvisos.getWidth());
        int alto = (int) (pnlAvisos.getHeight()*0.90);
        Point ubicacionVentana = pnlAvisos.getLocationOnScreen();
        if(ventanaRegistro == null || !ventanaRegistro.isVisible()) {
            ventanaRegistro = new RegistroCliente(this, false, ancho, alto, ubicacionVentana);  
            ventanaRegistro.setTitle("Registro de Reserva");
            ventanaRegistro.añadirHabitacionAReserva(numeroHabitacion);
            ventanaRegistro.setVisible(true);
        } else {
            if(ventanaRegistro.verificarHabitacionInstanciada(numeroHabitacion)) {
                int respuesta = JOptionPane.showConfirmDialog(this,"¿Desea añadir la habitacion "+numeroHabitacion+" a la reserva?");
                if(respuesta == JOptionPane.YES_OPTION) {
                ventanaRegistro.añadirHabitacionAReserva(numeroHabitacion);
                ventanaRegistro.toFront();
                }
            }
        }
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHabitaciones = new javax.swing.JPanel();
        btn501 = new javax.swing.JToggleButton();
        btn502 = new javax.swing.JToggleButton();
        btn503 = new javax.swing.JToggleButton();
        btn504 = new javax.swing.JToggleButton();
        btn401 = new javax.swing.JToggleButton();
        btn402 = new javax.swing.JToggleButton();
        btn403 = new javax.swing.JToggleButton();
        btn404 = new javax.swing.JToggleButton();
        btn301 = new javax.swing.JToggleButton();
        btn302 = new javax.swing.JToggleButton();
        btn303 = new javax.swing.JToggleButton();
        btn304 = new javax.swing.JToggleButton();
        btn201 = new javax.swing.JToggleButton();
        btn202 = new javax.swing.JToggleButton();
        btn203 = new javax.swing.JToggleButton();
        btn204 = new javax.swing.JToggleButton();
        btn101 = new javax.swing.JToggleButton();
        btn102 = new javax.swing.JToggleButton();
        btn103 = new javax.swing.JToggleButton();
        btn104 = new javax.swing.JToggleButton();
        pnlAvisos = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        pnlHabitaciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 150, 50, 150));
        pnlHabitaciones.setLayout(new java.awt.GridLayout(5, 4));

        btn501.setText("<html><br><br><br><br><br><br>501</html>");
        btn501.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn501);

        btn502.setText("<html><br><br><br><br><br><br>502</html>");
        btn502.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn502);

        btn503.setText("<html><br><br><br><br><br><br>503</html>");
        btn503.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn503);

        btn504.setText("<html><br><br><br><br><br><br>504</html>");
        btn504.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn504);

        btn401.setText("<html><br><br><br><br><br><br>401</html>");
        btn401.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn401);

        btn402.setText("<html><br><br><br><br><br><br>402</html>");
        btn402.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn402);

        btn403.setText("<html><br><br><br><br><br><br>403</html>");
        btn403.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn403);

        btn404.setText("<html><br><br><br><br><br><br>404</html>");
        btn404.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn404);

        btn301.setText("<html><br><br><br><br><br><br>301</html>");
        btn301.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn301);

        btn302.setText("<html><br><br><br><br><br><br>302</html>");
        btn302.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn302);

        btn303.setText("<html><br><br><br><br><br><br>303</html>");
        btn303.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn303);

        btn304.setText("<html><br><br><br><br><br><br>304</html>");
        btn304.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn304);

        btn201.setText("<html><br><br><br><br><br><br>201</html>");
        btn201.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn201);

        btn202.setText("<html><br><br><br><br><br><br>202</html>");
        btn202.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn202);

        btn203.setText("<html><br><br><br><br><br><br>203</html>");
        btn203.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn203);

        btn204.setText("<html><br><br><br><br><br><br>204</html>");
        btn204.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn204);

        btn101.setText("<html><br><br><br><br><br><br>101</html>");
        btn101.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn101);

        btn102.setText("<html><br><br><br><br><br><br>102</html>");
        btn102.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn102);

        btn103.setText("<html><br><br><br><br><br><br>103</html>");
        btn103.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn103);

        btn104.setText("<html><br><br><br><br><br><br>104</html>");
        btn104.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHabitaciones.add(btn104);

        getContentPane().add(pnlHabitaciones);

        pnlAvisos.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(pnlAvisos);

        jMenu1.setText("File");
        MenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JToggleButton btn101;
    private javax.swing.JToggleButton btn102;
    private javax.swing.JToggleButton btn103;
    private javax.swing.JToggleButton btn104;
    private javax.swing.JToggleButton btn201;
    private javax.swing.JToggleButton btn202;
    private javax.swing.JToggleButton btn203;
    private javax.swing.JToggleButton btn204;
    private javax.swing.JToggleButton btn301;
    private javax.swing.JToggleButton btn302;
    private javax.swing.JToggleButton btn303;
    private javax.swing.JToggleButton btn304;
    private javax.swing.JToggleButton btn401;
    private javax.swing.JToggleButton btn402;
    private javax.swing.JToggleButton btn403;
    private javax.swing.JToggleButton btn404;
    private javax.swing.JToggleButton btn501;
    private javax.swing.JToggleButton btn502;
    private javax.swing.JToggleButton btn503;
    private javax.swing.JToggleButton btn504;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel pnlAvisos;
    private javax.swing.JPanel pnlHabitaciones;
    // End of variables declaration//GEN-END:variables
}
