package com.hotelnaylamp.view.Moldes;

import com.hotelnaylamp.model.entities.Cliente;
import javax.swing.JOptionPane;


public class FichaCliente extends javax.swing.JPanel {
    private Cliente clienteGuardado;
    private PanelRegistroCliente panelRegistroCliente;

    public Cliente getClienteGuardado() {
        return clienteGuardado;
    }
    

    public FichaCliente(Cliente nuevoCliente, PanelRegistroCliente panelRegistroCLiente) {
        initComponents();
        this.clienteGuardado = nuevoCliente;
        this.panelRegistroCliente = panelRegistroCLiente;
        lblDocumento.setText(clienteGuardado.getDocumento());
        lblNombre.setText(clienteGuardado.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(210, 100));
        setMinimumSize(new java.awt.Dimension(210, 100));
        setPreferredSize(new java.awt.Dimension(210, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblDocumento.setBackground(new java.awt.Color(0, 0, 0));
        lblDocumento.setText("Documento");
        add(lblDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnEditarCliente.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(this::btnEditarClienteActionPerformed);
        add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, -1));

        btnEliminarCliente.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(this::btnEliminarClienteActionPerformed);
        add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        panelRegistroCliente.cargarDatosCliente(this.clienteGuardado,this);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed

        int resultado = JOptionPane.showConfirmDialog(this,"¿Desea eliminar cliente?");
        if(resultado == JOptionPane.YES_OPTION) {
            System.out.println("Boton Eliminado");
            panelRegistroCliente.eliminarFicha(this.clienteGuardado.getDocumento(),this);
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables


    public void actualizarLabels() {
        lblDocumento.setText(clienteGuardado.getDocumento());
        lblNombre.setText(clienteGuardado.getNombre());
    }



}
