package com.hotelnaylamp.view.Moldes;

import com.hotelnaylamp.controller.ClienteController;
import com.hotelnaylamp.controller.DetalleReservaController;
import com.hotelnaylamp.model.entities.Cliente;
import com.hotelnaylamp.util.CampoNumericoUtil;
import com.hotelnaylamp.util.PlaceholderUtil;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PanelRegistroCliente extends javax.swing.JPanel {

    private int habitacionAsignada;
    private FichaCliente fichaEnEdicion = null;
    private ArrayList<Cliente> listaClientes = new ArrayList<>();
    private ClienteController clienteController = new ClienteController();
    private DetalleReservaController detalleReservaController = new DetalleReservaController();
    
    public PanelRegistroCliente(int numeroHabitacion) {
        initComponents();
        btnCancelarEdicion.setVisible(false);
        this.habitacionAsignada = numeroHabitacion;
        
        inicializarPlaceholders();   // toda la configuración de placeholders
        inicializarCamposNumericos(); // CampoNumericoUtil
        inicializarFechas();          // spinners y combos de horas
        configurarEventos();          // ActionListeners de los combos

        actualizarPreciosYPagos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedorDatosHabitacion = new javax.swing.JPanel();
        cboTipoDocumento = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtProvincia = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        btnAgregarOEditarCliente = new javax.swing.JButton();
        btnCancelarEdicion = new javax.swing.JButton();
        sPnlClientes = new javax.swing.JScrollPane();
        pnlContenedorClientes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cboTipoHoraIngreso = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtCantidadPagada = new javax.swing.JTextField();
        cboTipoHoraSalida = new javax.swing.JComboBox<>();
        lblHoraEntrada = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        lblTiempoReservado = new javax.swing.JLabel();
        lblCantidadPagada = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtTiempoReservadoHora = new javax.swing.JTextField();
        txtTiempoReservadoDia = new javax.swing.JTextField();
        txtTiempoReservadoMes = new javax.swing.JTextField();
        cboHoraIngresoManual = new javax.swing.JComboBox<>();
        cboHoraSalidaManual = new javax.swing.JComboBox<>();
        spnDiaIngreso = new javax.swing.JSpinner();
        spnMesIngreso = new javax.swing.JSpinner();
        spnAnioIngreso = new javax.swing.JSpinner();
        spnDiaSalida = new javax.swing.JSpinner();
        spnMesSalida = new javax.swing.JSpinner();
        spnAnioSalida = new javax.swing.JSpinner();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedorDatosHabitacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Clientes"));

        cboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CE", "PTP" }));
        cboTipoDocumento.addActionListener(this::cboTipoDocumentoActionPerformed);

        txtDocumento.setColumns(10);
        txtDocumento.setText("Documento");
        txtDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        txtNombre.setColumns(10);
        txtNombre.setText("Nombre");

        txtDireccion.setText("Direccion");

        txtApellidoPaterno.setText("A. Paterno");

        txtDepartamento.setText("Departamento");

        txtProvincia.setText("Provincia");

        txtDistrito.setText("Distrito");

        txtNacionalidad.setEditable(false);
        txtNacionalidad.setText("PERUANO");

        txtApellidoMaterno.setText("A. Materno");

        btnAgregarOEditarCliente.setBackground(new java.awt.Color(153, 255, 102));
        btnAgregarOEditarCliente.setText("Agregar Cliente");
        btnAgregarOEditarCliente.addActionListener(this::btnAgregarOEditarClienteActionPerformed);

        btnCancelarEdicion.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarEdicion.setText("Cancelar Edicion");
        btnCancelarEdicion.addActionListener(this::btnCancelarEdicionActionPerformed);

        javax.swing.GroupLayout pnlContenedorDatosHabitacionLayout = new javax.swing.GroupLayout(pnlContenedorDatosHabitacion);
        pnlContenedorDatosHabitacion.setLayout(pnlContenedorDatosHabitacionLayout);
        pnlContenedorDatosHabitacionLayout.setHorizontalGroup(
            pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarOEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlContenedorDatosHabitacionLayout.setVerticalGroup(
            pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarOEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlContenedorDatosHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 200));

        pnlContenedorClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Clientes Hospedados:"));
        pnlContenedorClientes.setLayout(new java.awt.GridLayout(1, 0));
        sPnlClientes.setViewportView(pnlContenedorClientes);

        add(sPnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 660, 130));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de Reserva"));

        cboTipoHoraIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora del Sistema", "Hora Manual" }));

        txtPrecio.setColumns(15);
        txtPrecio.setText("0.0");
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });

        txtCantidadPagada.setColumns(10);
        txtCantidadPagada.setText("0.0");
        txtCantidadPagada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadPagadaFocusLost(evt);
            }
        });

        cboTipoHoraSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Predeterminado", "Salida Manual" }));

        lblHoraEntrada.setText("Hora de Ingreso:");

        lblHoraSalida.setText("Hora de Salida:");

        lblTiempoReservado.setText("Tiempo Reservado:");

        lblCantidadPagada.setText("Cantidad Pagada:");

        lblPrecio.setText("Precio:");

        txtTiempoReservadoHora.setColumns(5);
        txtTiempoReservadoHora.setText("12");
        txtTiempoReservadoHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Hora(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N

        txtTiempoReservadoDia.setColumns(5);
        txtTiempoReservadoDia.setText("0");
        txtTiempoReservadoDia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dia(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N

        txtTiempoReservadoMes.setColumns(5);
        txtTiempoReservadoMes.setText("0");
        txtTiempoReservadoMes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Mes(es)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N

        cboHoraIngresoManual.setEditable(true);
        cboHoraIngresoManual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHoraIngresoManual.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        cboHoraIngresoManual.setEnabled(false);

        cboHoraSalidaManual.setEditable(true);
        cboHoraSalidaManual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHoraSalidaManual.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        cboHoraSalidaManual.setEnabled(false);

        spnDiaIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        spnDiaIngreso.setEnabled(false);

        spnMesIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Mes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        spnMesIngreso.setEnabled(false);

        spnAnioIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Año", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        spnAnioIngreso.setEnabled(false);

        spnDiaSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Dia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        spnDiaSalida.setEnabled(false);

        spnMesSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Mes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        spnMesSalida.setEnabled(false);

        spnAnioSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Año", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 8))); // NOI18N
        spnAnioSalida.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHoraEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipoHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnMesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnAnioIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboHoraIngresoManual, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTiempoReservado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoReservadoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTiempoReservadoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTiempoReservadoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblHoraSalida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboTipoHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblCantidadPagada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidadPagada, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(spnMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboHoraSalidaManual, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraEntrada)
                    .addComponent(cboTipoHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboHoraIngresoManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnDiaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnMesIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAnioIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiempoReservadoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempoReservadoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTiempoReservadoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempoReservado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraSalida)
                    .addComponent(cboHoraSalidaManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnDiaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnMesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio)
                    .addComponent(lblCantidadPagada)
                    .addComponent(txtCantidadPagada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 660, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        String documentoActual = txtDocumento.getText();
        String documentoElegido = cboTipoDocumento.getSelectedItem().toString();

        int longitudMinima = clienteController.obtenerLongitudMinimaBusqueda(documentoElegido);

        // Buscamos cuando alcanza o supera la longitud mínima
        if(documentoActual.length() >= longitudMinima) {
            Cliente clienteInstanciado = clienteController.buscarClientePorDocumento(documentoActual, 
                                                            documentoElegido);
            if(clienteInstanciado != null) {
                txtNombre.setText(clienteInstanciado.getNombre());
                txtApellidoPaterno.setText(clienteInstanciado.getApellidoPaterno());
                txtApellidoMaterno.setText(clienteInstanciado.getApellidoMaterno());
                txtDireccion.setText(clienteInstanciado.getDireccion());
                txtDepartamento.setText(clienteInstanciado.getDepartamento());
                txtProvincia.setText(clienteInstanciado.getProvincia());
                txtDistrito.setText(clienteInstanciado.getDistrito());
                txtNacionalidad.setText(clienteInstanciado.getNacionalidad());
            }
        }
    }//GEN-LAST:event_txtDocumentoKeyReleased

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isDigit(tecla)) {
            evt.consume();
            return;
        }

        String documentoElegido = cboTipoDocumento.getSelectedItem().toString();
        String textoActual = txtDocumento.getText();

        int longitudMaxima = clienteController.obtenerLongitudMaximaDocumento(documentoElegido);
        if(textoActual.length() >= longitudMaxima) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void btnAgregarOEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarOEditarClienteActionPerformed
        //Validar Cliente
        String errorMensajeCliente = clienteController.validarDatosCliente(cboTipoDocumento.getSelectedItem().toString(),
                                                        txtDocumento.getText(),txtNombre.getText(),
                                                        txtApellidoPaterno.getText(),txtApellidoMaterno.getText(),
                                                        txtDireccion.getText());
            
        if(errorMensajeCliente!=null){
            JOptionPane.showMessageDialog(this,errorMensajeCliente);
            return;
        }
            
        if(fichaEnEdicion == null) {
            //Crear Cliente
            Cliente nuevocliente = clienteController.crearCliente(cboTipoDocumento.getSelectedItem().toString(),
                                                        txtDocumento.getText(),txtNombre.getText(),
                                                        txtApellidoPaterno.getText(),txtApellidoMaterno.getText(),
                                                        txtDireccion.getText(),txtDepartamento.getText(),
                                                        txtProvincia.getText(),txtDistrito.getText(),
                                                        txtNacionalidad.getText());
            listaClientes.add(nuevocliente);
            
            FichaCliente nuevaFicha = new FichaCliente(nuevocliente,this);
            pnlContenedorClientes.add(nuevaFicha);
            pnlContenedorClientes.revalidate();
            pnlContenedorClientes.repaint();
            limpiarFormulario();
            
        } else {
            //Editar Cliente
            clienteController.actualizarDatosCliente(fichaEnEdicion.getClienteGuardado(),
                                cboTipoDocumento.getSelectedItem().toString(),txtDocumento.getText(),
                                txtNombre.getText(),txtApellidoPaterno.getText(),txtApellidoMaterno.getText(),
                                txtDireccion.getText(),txtDepartamento.getText(),txtProvincia.getText(),
                                txtDistrito.getText(),txtNacionalidad.getText());
            
            fichaEnEdicion.actualizarLabels();
            limpiarFormulario();
            fichaEnEdicion = null;
            renombrarBotones("no editando");
        }
    }//GEN-LAST:event_btnAgregarOEditarClienteActionPerformed

    private void btnCancelarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicionActionPerformed
        if(fichaEnEdicion != null){
            pnlContenedorClientes.revalidate();
            pnlContenedorClientes.repaint();
            limpiarFormulario();
            fichaEnEdicion = null;
            renombrarBotones("no editando");
        }
    }//GEN-LAST:event_btnCancelarEdicionActionPerformed

    private void cboTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDocumentoActionPerformed
        establecerNacionalidad(cboTipoDocumento.getSelectedItem().toString());
    }//GEN-LAST:event_cboTipoDocumentoActionPerformed

    private void txtCantidadPagadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadPagadaFocusLost
        String errorMensaje = detalleReservaController.validarCantidadPagadaHabitacion(txtCantidadPagada.getText(),
            habitacionAsignada,txtPrecio.getText());
        if(errorMensaje!=null){
            JOptionPane.showMessageDialog(this,errorMensaje);
            return;
        }
    }//GEN-LAST:event_txtCantidadPagadaFocusLost

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        String errorMensaje = detalleReservaController.validarPrecioHabitacion(txtPrecio.getText(), habitacionAsignada);
        if(errorMensaje!=null){
            JOptionPane.showMessageDialog(this,errorMensaje);
            return;
        }
        txtCantidadPagada.setText(txtPrecio.getText());
    }//GEN-LAST:event_txtPrecioFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarOEditarCliente;
    private javax.swing.JButton btnCancelarEdicion;
    private javax.swing.JComboBox<String> cboHoraIngresoManual;
    private javax.swing.JComboBox<String> cboHoraSalidaManual;
    private javax.swing.JComboBox<String> cboTipoDocumento;
    private javax.swing.JComboBox<String> cboTipoHoraIngreso;
    private javax.swing.JComboBox<String> cboTipoHoraSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadPagada;
    private javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTiempoReservado;
    private javax.swing.JPanel pnlContenedorClientes;
    private javax.swing.JPanel pnlContenedorDatosHabitacion;
    private javax.swing.JScrollPane sPnlClientes;
    private javax.swing.JSpinner spnAnioIngreso;
    private javax.swing.JSpinner spnAnioSalida;
    private javax.swing.JSpinner spnDiaIngreso;
    private javax.swing.JSpinner spnDiaSalida;
    private javax.swing.JSpinner spnMesIngreso;
    private javax.swing.JSpinner spnMesSalida;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCantidadPagada;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtTiempoReservadoDia;
    private javax.swing.JTextField txtTiempoReservadoHora;
    private javax.swing.JTextField txtTiempoReservadoMes;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        txtDocumento.setText("Documento");
        txtNombre.setText("Nombre");
        txtApellidoPaterno.setText("A. Paterno");
        txtApellidoMaterno.setText("A. Materno");
        txtDireccion.setText("Direccion");
        txtDepartamento.setText("Departamento");
        txtProvincia.setText("Provincia");
        txtDistrito.setText("Distrito");
        txtNacionalidad.setText("PERUANO");
        cboTipoDocumento.setSelectedIndex(0);
    }
    
    public void cargarDatosCliente(Cliente clienteAEditar,FichaCliente ficha) {
        txtDocumento.setText(clienteAEditar.getDocumento());
        txtNombre.setText(clienteAEditar.getNombre());
        txtApellidoPaterno.setText(clienteAEditar.getApellidoPaterno());
        txtApellidoMaterno.setText(clienteAEditar.getApellidoMaterno());
        txtDireccion.setText(clienteAEditar.getDireccion());
        txtDepartamento.setText(clienteAEditar.getDepartamento());
        txtProvincia.setText(clienteAEditar.getProvincia());
        txtDistrito.setText(clienteAEditar.getDistrito());
        txtNacionalidad.setText(clienteAEditar.getNacionalidad());
        cboTipoDocumento.setSelectedItem(clienteAEditar.getTipoDocumento());
        this.fichaEnEdicion = ficha;
        renombrarBotones("editando");
    }
    
    public void renombrarBotones(String estado) {
        if(estado.equals("editando")) {
           btnCancelarEdicion.setVisible(true);
           btnAgregarOEditarCliente.setText("Editar Cliente"); 
        } else {
           btnCancelarEdicion.setVisible(false);
           btnAgregarOEditarCliente.setText("Agregar Cliente"); 
        }
        
    }
    
    public void eliminarFicha(String documento, FichaCliente ficha) {
        for( int i = 0 ; i < listaClientes.size(); i++) {
            if(listaClientes.get(i).getDocumento().equals(documento)){
                listaClientes.remove(i);
                break;
            }
        }
        pnlContenedorClientes.remove(ficha);
        pnlContenedorClientes.revalidate();
        pnlContenedorClientes.repaint();
 
    }
    
    public float convertirCantidadPagada() {
        String error = detalleReservaController.validarCantidadPagadaHabitacion(txtCantidadPagada.getText(), 
                                                        habitacionAsignada, txtPrecio.getText());
        if (error != null) {
            return 0;
        }
        return Float.parseFloat(txtCantidadPagada.getText());
    }
    
    public void actualizarPreciosYPagos() {
        String precio = detalleReservaController.obtenerPrecioInicial(habitacionAsignada);
        txtPrecio.setText(precio);
        txtCantidadPagada.setText(precio);
    }

    
    public void establecerNacionalidad(String tipoDocumento) {
        boolean editable = clienteController.esNacionalidadEditable(tipoDocumento);
        txtNacionalidad.setEditable(editable);
        if(editable) {
            txtNacionalidad.setText("Nacionalidad");
        } else {
            txtNacionalidad.setText("PERUANO");
        }
    }
    
    public LocalDateTime obtenerFechaEntrada() {
    return detalleReservaController.obtenerFechaEntrada(
        cboTipoHoraIngreso.getSelectedItem().toString(),
        (int) spnDiaIngreso.getValue(),
        (int) spnMesIngreso.getValue(),
        (int) spnAnioIngreso.getValue(),
        cboHoraIngresoManual.getSelectedItem().toString()
    );
}
    
    public LocalDateTime establecerFechaSalida() {
        return detalleReservaController.establecerFechaSalida(
            cboTipoHoraIngreso.getSelectedItem().toString(),
            cboTipoHoraSalida.getSelectedItem().toString(),
            txtTiempoReservadoHora.getText(),
            txtTiempoReservadoDia.getText(),
            txtTiempoReservadoMes.getText(),
            habitacionAsignada,
            (int) spnDiaIngreso.getValue(),
            (int) spnMesIngreso.getValue(),
            (int) spnAnioIngreso.getValue(),
            cboHoraIngresoManual.getSelectedItem().toString(),
            (int) spnDiaSalida.getValue(),
            (int) spnMesSalida.getValue(),
            (int) spnAnioSalida.getValue(),
            cboHoraSalidaManual.getSelectedItem().toString()
        );
    }
    
    public ArrayList<Cliente> obtenerClientes() {
        return new ArrayList<>(listaClientes); 
    }
    
    public int getHabitacionAsignada() {
        return habitacionAsignada;
    }
    
    private void inicializarPlaceholders(){
        PlaceholderUtil.aplicar(txtDocumento, "Documento");
        PlaceholderUtil.aplicar(txtNombre, "Nombre");
        PlaceholderUtil.aplicar(txtApellidoPaterno, "A. Paterno");
        PlaceholderUtil.aplicar(txtApellidoMaterno, "A. Materno");
        PlaceholderUtil.aplicar(txtDireccion, "Direccion");
        PlaceholderUtil.aplicar(txtDepartamento, "Departamento");
        PlaceholderUtil.aplicar(txtProvincia, "Provincia");
        PlaceholderUtil.aplicar(txtDistrito, "Distrito");
        PlaceholderUtil.aplicar(txtNacionalidad, "PERUANO");
        PlaceholderUtil.aplicar(txtPrecio, "0.0");
        PlaceholderUtil.aplicar(txtCantidadPagada, "0.0");
    }
    
    private void inicializarCamposNumericos(){
        CampoNumericoUtil.soloNumeros(txtTiempoReservadoHora);
        CampoNumericoUtil.soloNumeros(txtTiempoReservadoDia);
        CampoNumericoUtil.soloNumeros(txtTiempoReservadoMes);
        CampoNumericoUtil.soloNumerosDecimales(txtPrecio);
        CampoNumericoUtil.soloNumerosDecimales(txtCantidadPagada);
    }
    
    private void inicializarFechas(){
        LocalDate hoy = java.time.LocalDate.now();
        spnDiaIngreso.setValue(hoy.getDayOfMonth());
        spnMesIngreso.setValue(hoy.getMonthValue());
        spnAnioIngreso.setValue(hoy.getYear());
        spnDiaSalida.setValue(hoy.getDayOfMonth());
        spnMesSalida.setValue(hoy.getMonthValue());
        spnAnioSalida.setValue(hoy.getYear());
        // Cargar las 48 horas (en punto y media) en los combos manuales
        String[] horas = {
            "0:00","0:30","1:00","1:30","2:00","2:30","3:00","3:30",
            "4:00","4:30","5:00","5:30","6:00","6:30","7:00","7:30",
            "8:00","8:30","9:00","9:30","10:00","10:30","11:00","11:30",
            "12:00","12:30","13:00","13:30","14:00","14:30","15:00","15:30",
            "16:00","16:30","17:00","17:30","18:00","18:30","19:00","19:30",
            "20:00","20:30","21:00","21:30","22:00","22:30","23:00","23:30"
        };
        cboHoraIngresoManual.setModel(new javax.swing.DefaultComboBoxModel<>(horas));
        cboHoraSalidaManual.setModel(new javax.swing.DefaultComboBoxModel<>(horas));
    }
    
    private void configurarEventos(){
        cboTipoHoraIngreso.addActionListener(e -> {
            // Si el usuario no eligió "Hora del Sistema", habilitamos los campos manuales
            boolean esManual = !cboTipoHoraIngreso.getSelectedItem().toString()
                                                  .equals("Hora del Sistema");
            spnDiaIngreso.setEnabled(esManual);
            spnMesIngreso.setEnabled(esManual);
            spnAnioIngreso.setEnabled(esManual);
            cboHoraIngresoManual.setEnabled(esManual);
        });

        // Lógica para habilitar/deshabilitar campos de salida manual
        cboTipoHoraSalida.addActionListener(e -> {
            // Si el usuario no eligió "Predeterminado", habilitamos los campos manuales
            // y deshabilitamos el tiempo reservado porque ya no tiene sentido
            boolean esManual = !cboTipoHoraSalida.getSelectedItem().toString()
                                                  .equals("Predeterminado");
            spnDiaSalida.setEnabled(esManual);
            spnMesSalida.setEnabled(esManual);
            spnAnioSalida.setEnabled(esManual);
            cboHoraSalidaManual.setEnabled(esManual);

            // El tiempo reservado solo tiene sentido cuando la salida es predeterminada
            txtTiempoReservadoHora.setEnabled(!esManual);
            txtTiempoReservadoDia.setEnabled(!esManual);
            txtTiempoReservadoMes.setEnabled(!esManual);
        });   
    }
}
