package com.hotelnaylamp.view.Moldes;

import com.hotelnaylamp.controller.ClienteController;
import com.hotelnaylamp.controller.HabitacionController;
import com.hotelnaylamp.model.entities.Cliente;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PanelRegistroCliente extends javax.swing.JPanel {

    private int habitacionAsignada;
    private FichaCliente fichaEnEdicion = null;
    private ArrayList<Cliente> listaClientes = new ArrayList<>();
    private ClienteController clienteController = new ClienteController();
    private HabitacionController habitacionController = new HabitacionController();
    
    public PanelRegistroCliente(int numeroHabitacion) {
        initComponents();
        btnCancelarEdicion.setVisible(false);
        this.habitacionAsignada = numeroHabitacion;
        actualizarPreciosyPagos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedorDatosHabitacion = new javax.swing.JPanel();
        cboTipoDocumento = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();
        txtProvincia = new javax.swing.JTextField();
        txtDistrito = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        btnAgregarOEditarCliente = new javax.swing.JButton();
        btnCancelarEdicion = new javax.swing.JButton();
        sPnlClientes = new javax.swing.JScrollPane();
        pnlContenedorClientes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cboHoraIngreso = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtCantidadPagada = new javax.swing.JTextField();
        cboHoraSalida = new javax.swing.JComboBox<>();
        lblHoraEntrada = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        lblTiempoReservado = new javax.swing.JLabel();
        lblCantidadPagada = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtTiempoReservadoHora = new javax.swing.JTextField();
        txtTiempoReservadoDia = new javax.swing.JTextField();
        txtTiempoReservadoMes = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedorDatosHabitacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Clientes"));

        cboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CE", "PTP" }));
        cboTipoDocumento.addActionListener(this::cboTipoDocumentoActionPerformed);

        txtDocumento.setColumns(10);
        txtDocumento.setText("Documento");
        txtDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDocumentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDocumentoFocusLost(evt);
            }
        });
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        txtNombre.setColumns(10);
        txtNombre.setText("Nombre");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        txtDireccion.setText("Direccion");
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });

        txtApellidoPaterno.setText("A. Paterno");
        txtApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoPaternoFocusLost(evt);
            }
        });

        txtDepartamento.setText("Departamento");
        txtDepartamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepartamentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepartamentoFocusLost(evt);
            }
        });

        txtProvincia.setText("Provincia");
        txtProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProvinciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProvinciaFocusLost(evt);
            }
        });

        txtDistrito.setText("Distrito");
        txtDistrito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDistritoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDistritoFocusLost(evt);
            }
        });

        txtNacionalidad.setEditable(false);
        txtNacionalidad.setText("PERUANO");
        txtNacionalidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNacionalidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNacionalidadFocusLost(evt);
            }
        });

        txtApellidoMaterno.setText("A. Materno");
        txtApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoMaternoFocusLost(evt);
            }
        });

        btnAgregarOEditarCliente.setBackground(new java.awt.Color(153, 255, 102));
        btnAgregarOEditarCliente.setText("Agregar Cliente");
        btnAgregarOEditarCliente.addActionListener(this::btnAgregarOEditarClienteActionPerformed);

        btnCancelarEdicion.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarEdicion.setText("Cancelar Edicion");
        btnCancelarEdicion.addActionListener(this::btnCancelarEdicionActionPerformed);

        javax.swing.GroupLayout pnlContenedorDatosHabitacionLayout = new javax.swing.GroupLayout(pnlContenedorDatosHabitacion);
        pnlContenedorDatosHabitacion.setLayout(pnlContenedorDatosHabitacionLayout);
        pnlContenedorDatosHabitacionLayout.setHorizontalGroup(
            pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtProvincia))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtDistrito))
                        .addGap(254, 254, 254))
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                                .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                                .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregarOEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenedorDatosHabitacionLayout.setVerticalGroup(
            pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenedorDatosHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContenedorDatosHabitacionLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAgregarOEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlContenedorDatosHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 220));

        pnlContenedorClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Clientes Hospedados:"));
        pnlContenedorClientes.setLayout(new java.awt.GridLayout(1, 0));
        sPnlClientes.setViewportView(pnlContenedorClientes);

        add(sPnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 660, 130));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de Reserva"));

        cboHoraIngreso.setEditable(true);
        cboHoraIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hora del Sistema", " " }));

        txtPrecio.setColumns(15);
        txtPrecio.setText("0.0");
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });

        txtCantidadPagada.setColumns(10);
        txtCantidadPagada.setText("0.0");
        txtCantidadPagada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantidadPagadaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadPagadaFocusLost(evt);
            }
        });

        cboHoraSalida.setEditable(true);
        cboHoraSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Predeterminado" }));

        lblHoraEntrada.setText("Hora de Ingreso:");

        lblHoraSalida.setText("Hora de Salida");

        lblTiempoReservado.setText("Tiempo Reservado:");

        lblCantidadPagada.setText("Cantidad Pagada:");

        lblPrecio.setText("Precio:");

        txtTiempoReservadoHora.setColumns(5);
        txtTiempoReservadoHora.setText("12");
        txtTiempoReservadoHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora(s)"));

        txtTiempoReservadoDia.setColumns(5);
        txtTiempoReservadoDia.setText("0");
        txtTiempoReservadoDia.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia(s)"));

        txtTiempoReservadoMes.setColumns(5);
        txtTiempoReservadoMes.setText("0");
        txtTiempoReservadoMes.setBorder(javax.swing.BorderFactory.createTitledBorder("Mes(es)"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraEntrada))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtTiempoReservadoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoReservadoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTiempoReservadoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTiempoReservado)
                        .addGap(68, 68, 68)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoraSalida)
                    .addComponent(cboHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lblCantidadPagada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadPagada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblHoraSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblHoraEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTiempoReservado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoReservadoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempoReservadoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempoReservadoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadPagada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadPagada)
                    .addComponent(lblPrecio))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 660, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocumentoFocusGained
        if(txtDocumento.getText().equals("Documento")) {
            txtDocumento.setText("");
        }
    }//GEN-LAST:event_txtDocumentoFocusGained

    private void txtDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocumentoFocusLost
        if(txtDocumento.getText().equals("")) {
            txtDocumento.setText("Documento");
        }
    }//GEN-LAST:event_txtDocumentoFocusLost

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        Cliente clienteInstanciado = null;
        String documentoActual = txtDocumento.getText();
        String documentoElegido = cboTipoDocumento.getSelectedItem().toString();

        if(documentoElegido.equals("DNI") && documentoActual.length() == 8) {
            clienteInstanciado = clienteController.buscarClientePorDocumento(documentoActual,documentoElegido);
        }

        if(documentoElegido.equals("CE") && documentoActual.length() == 9) {
            clienteInstanciado = clienteController.buscarClientePorDocumento(documentoActual,documentoElegido);
        }

        if(documentoElegido.equals("PTP") && (documentoActual.length() > 5 && documentoActual.length() < 10 )){
            clienteInstanciado = clienteController.buscarClientePorDocumento(documentoActual,documentoElegido);
        }
        
        if(clienteInstanciado!=null) {
            txtNombre.setText(clienteInstanciado.getNombre());
            txtApellidoPaterno.setText(clienteInstanciado.getApellidoPaterno());
            txtApellidoMaterno.setText(clienteInstanciado.getApellidoMaterno());
            txtDireccion.setText(clienteInstanciado.getDireccion());
            txtDepartamento.setText(clienteInstanciado.getDepartamento());
            txtProvincia.setText(clienteInstanciado.getProvincia());
            txtDistrito.setText(clienteInstanciado.getDistrito());
            txtNacionalidad.setText(clienteInstanciado.getNacionalidad());
        }
        
    }//GEN-LAST:event_txtDocumentoKeyReleased

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isDigit(tecla)) {
            evt.consume();
        }

        String documentoElegido = cboTipoDocumento.getSelectedItem().toString();
        String textoActual = txtDocumento.getText().toString();

        if(documentoElegido.equals("DNI") && textoActual.length() >= 8) {
            evt.consume();
        }

        if(documentoElegido.equals("CE") && textoActual.length() >= 9) {
            evt.consume();
        }

        if(documentoElegido.equals("PTP") && textoActual.length() >= 10 ){
            evt.consume();
        }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        if(txtNombre.getText().equals("Nombre")) {
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(txtNombre.getText().equals("")) {
            txtNombre.setText("Nombre");
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusGained
        if(txtDireccion.getText().equals("Direccion")){
            txtDireccion.setText("");
        }
    }//GEN-LAST:event_txtDireccionFocusGained

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        if(txtDireccion.getText().equals("")){
            txtDireccion.setText("Direccion");
        }
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtApellidoPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPaternoFocusGained
        if(txtApellidoPaterno.getText().equals("A. Paterno")){
            txtApellidoPaterno.setText("");
        }
    }//GEN-LAST:event_txtApellidoPaternoFocusGained

    private void txtApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoPaternoFocusLost
        if(txtApellidoPaterno.getText().equals("")){
            txtApellidoPaterno.setText("A. Paterno");
        }
    }//GEN-LAST:event_txtApellidoPaternoFocusLost

    private void txtDepartamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepartamentoFocusGained
        if(txtDepartamento.getText().equals("Departamento")){
            txtDepartamento.setText("");
        }
    }//GEN-LAST:event_txtDepartamentoFocusGained

    private void txtDepartamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepartamentoFocusLost
        if(txtDepartamento.getText().equals("")){
            txtDepartamento.setText("Departamento");
        }
    }//GEN-LAST:event_txtDepartamentoFocusLost

    private void txtProvinciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProvinciaFocusGained
        if(txtProvincia.getText().equals("Provincia")){
            txtProvincia.setText("");
        }
    }//GEN-LAST:event_txtProvinciaFocusGained

    private void txtProvinciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProvinciaFocusLost

        if(txtProvincia.getText().equals("")){
            txtProvincia.setText("Provincia");
        }

    }//GEN-LAST:event_txtProvinciaFocusLost

    private void txtDistritoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDistritoFocusGained
        if(txtDistrito.getText().equals("Distrito")){
            txtDistrito.setText("");
        }
    }//GEN-LAST:event_txtDistritoFocusGained

    private void txtDistritoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDistritoFocusLost
        if(txtDistrito.getText().equals("")){
            txtDistrito.setText("Distrito");
        }
    }//GEN-LAST:event_txtDistritoFocusLost

    private void txtNacionalidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNacionalidadFocusGained

        if(txtNacionalidad.getText().equals("Nacionalidad")){
            txtNacionalidad.setText("");
        }
    }//GEN-LAST:event_txtNacionalidadFocusGained

    private void txtNacionalidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNacionalidadFocusLost
        if(txtNacionalidad.getText().equals("")){
            txtNacionalidad.setText("Nacionalidad");
        }
    }//GEN-LAST:event_txtNacionalidadFocusLost

    private void txtApellidoMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMaternoFocusGained
        if(txtApellidoMaterno.getText().equals("A. Materno")){
            txtApellidoMaterno.setText("");
        }
    }//GEN-LAST:event_txtApellidoMaternoFocusGained

    private void txtApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoMaternoFocusLost
        if(txtApellidoMaterno.getText().equals("")){
            txtApellidoMaterno.setText("A. Materno");
        }
    }//GEN-LAST:event_txtApellidoMaternoFocusLost

    private void btnAgregarOEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarOEditarClienteActionPerformed
        if(fichaEnEdicion == null) {
            Cliente nuevocliente = new Cliente(cboTipoDocumento.getSelectedItem().toString(),
                txtDocumento.getText(),txtNombre.getText(),
                txtApellidoPaterno.getText(),txtApellidoMaterno.getText(),
                txtDireccion.getText(),txtDepartamento.getText(),
                txtProvincia.getText(),txtDistrito.getText(),
                txtNacionalidad.getText());
            listaClientes.add(nuevocliente);
            FichaCliente nuevaFicha = new FichaCliente(nuevocliente,this);
            pnlContenedorClientes.add(nuevaFicha);
            pnlContenedorClientes.revalidate();
            pnlContenedorClientes.repaint();
            limpiarFormulario();
        } else {
            Cliente clienteAActualizar = fichaEnEdicion.getClienteGuardado();
            clienteAActualizar.setTipoDocumento(cboTipoDocumento.getSelectedItem().toString());
            clienteAActualizar.setDocumento(txtDocumento.getText());
            clienteAActualizar.setNombre(txtNombre.getText());
            clienteAActualizar.setApellidoPaterno(txtApellidoPaterno.getText());
            clienteAActualizar.setApellidoMaterno(txtApellidoMaterno.getText());
            clienteAActualizar.setDireccion(txtDireccion.getText());
            clienteAActualizar.setDepartamento(txtDepartamento.getText());
            clienteAActualizar.setProvincia(txtProvincia.getText());
            clienteAActualizar.setDistrito(txtDistrito.getText());
            clienteAActualizar.setNacionalidad(txtNacionalidad.getText());
            fichaEnEdicion.actualizarLabels();
            limpiarFormulario();
            fichaEnEdicion = null;
            editarBotones("no editando");
        }
    }//GEN-LAST:event_btnAgregarOEditarClienteActionPerformed

    private void btnCancelarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicionActionPerformed
        if(fichaEnEdicion != null){
            pnlContenedorClientes.revalidate();
            pnlContenedorClientes.repaint();
            limpiarFormulario();
            fichaEnEdicion = null;
            editarBotones("no editando");
        }
    }//GEN-LAST:event_btnCancelarEdicionActionPerformed

    private void txtPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusGained
        if(txtPrecio.getText().equalsIgnoreCase("Precio")) {
            txtPrecio.setText("");
        }
    }//GEN-LAST:event_txtPrecioFocusGained

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        if(txtPrecio.getText().equals("")) {
            txtPrecio.setText("Precio ");
        }
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtCantidadPagadaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadPagadaFocusGained
        if(txtCantidadPagada.getText().equalsIgnoreCase("Cantidad Pagada")) {
            txtCantidadPagada.setText("");
        }
    }//GEN-LAST:event_txtCantidadPagadaFocusGained

    private void txtCantidadPagadaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadPagadaFocusLost
        if(txtCantidadPagada.getText().equals("")) {
            txtCantidadPagada.setText("Cantidad Pagada");
        }
    }//GEN-LAST:event_txtCantidadPagadaFocusLost

    private void cboTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDocumentoActionPerformed
        establecerNacionalidad(cboTipoDocumento.getSelectedItem().toString());
    }//GEN-LAST:event_cboTipoDocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarOEditarCliente;
    private javax.swing.JButton btnCancelarEdicion;
    private javax.swing.JComboBox<String> cboHoraIngreso;
    private javax.swing.JComboBox<String> cboHoraSalida;
    private javax.swing.JComboBox<String> cboTipoDocumento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadPagada;
    private javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTiempoReservado;
    private javax.swing.JPanel pnlContenedorClientes;
    private javax.swing.JPanel pnlContenedorDatosHabitacion;
    private javax.swing.JScrollPane sPnlClientes;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCantidadPagada;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtTiempoReservadoDia;
    private javax.swing.JTextField txtTiempoReservadoHora;
    private javax.swing.JTextField txtTiempoReservadoMes;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        txtDocumento.setText("Documento");
        txtNombre.setText("Nombre");
        txtApellidoPaterno.setText("A. Paterno");
        txtApellidoMaterno.setText("A. Materno");
        txtDireccion.setText("Direccion");
        txtDepartamento.setText("Departamento");
        txtProvincia.setText("Provincia");
        txtDistrito.setText("Distrito");
        txtNacionalidad.setText("Nacionalidad");
        cboTipoDocumento.setSelectedIndex(0);
    }
    
    public void cargarDatosCliente(Cliente clienteAEditar,FichaCliente ficha) {
        txtDocumento.setText(clienteAEditar.getDocumento());
        txtNombre.setText(clienteAEditar.getNombre());
        txtApellidoPaterno.setText(clienteAEditar.getApellidoPaterno());
        txtApellidoMaterno.setText(clienteAEditar.getApellidoMaterno());
        txtDireccion.setText(clienteAEditar.getDireccion());
        txtDepartamento.setText(clienteAEditar.getDepartamento());
        txtProvincia.setText(clienteAEditar.getProvincia());
        txtDistrito.setText(clienteAEditar.getDistrito());
        txtNacionalidad.setText(clienteAEditar.getNacionalidad());
        cboTipoDocumento.setSelectedItem(clienteAEditar.getTipoDocumento());
        this.fichaEnEdicion = ficha;
        editarBotones("editando");
    }
    
    public void editarBotones(String estado) {
        if(estado.equals("editando")) {
           btnCancelarEdicion.setVisible(true);
           btnAgregarOEditarCliente.setText("Editar Cliente"); 
        } else {
           btnCancelarEdicion.setVisible(false);
           btnAgregarOEditarCliente.setText("Agregar Cliente"); 
        }
        
    }
    
    public void eliminarFicha(String documento, FichaCliente ficha) {
        for( int i = 0 ; i < listaClientes.size(); i++) {
            if(listaClientes.get(i).getDocumento().equals(documento)){
                listaClientes.remove(i);
                break;
            }
        }
        pnlContenedorClientes.remove(ficha);
        pnlContenedorClientes.revalidate();
        pnlContenedorClientes.repaint();
 
    }
    
    public float obtenerCantidadPagada() {
        float precioFinal = Float.parseFloat(txtCantidadPagada.getText());
        return precioFinal;
    }
    
    public void actualizarPreciosyPagos() {
        txtPrecio.setText(habitacionController.obtenerPrecioHabitacion(Integer.toString(habitacionAsignada)));
        txtCantidadPagada.setText(txtPrecio.getText());
    }
    
    public void establecerNacionalidad(String tipoDocumento) {
        if(tipoDocumento.equals("DNI")) {
            txtNacionalidad.setEditable(false);
        } else {
            txtNacionalidad.setEditable(true);
            txtNacionalidad.setText("Nacionalidad");
        }
    }
    
    public LocalDateTime obtenerFechaEntrada() {
        String opcionElegida = cboHoraIngreso.getSelectedItem().toString();
        LocalDate fechaHoy = LocalDate.now();
        LocalTime horaIngreso;

        if(opcionElegida.equals("Hora del Sistema")) {
            // Captura la hora exacta en el momento en que se presiona "Crear Reserva"
            horaIngreso = LocalTime.now().withSecond(0).withNano(0);
        } else {
            // Convierte el texto manual (ej. "22:00") a tiempo
            horaIngreso = LocalTime.parse(opcionElegida);
        }
        return LocalDateTime.of(fechaHoy, horaIngreso);
    }
    
    public LocalDateTime establecerFechaSalida() {
        String opcionElegida = cboHoraSalida.getSelectedItem().toString();
        if(opcionElegida.equals("Predeterminado")) {
            LocalDateTime fechaEntrada =  obtenerFechaEntrada();
            LocalDateTime fechaSalida = fechaEntrada;
            Long auxiliarTiempoReservado;
            if(!txtTiempoReservadoHora.getText().equals("0")) {
                auxiliarTiempoReservado = Long.parseLong(txtTiempoReservadoHora.getText());
                fechaSalida = fechaSalida.plusHours(auxiliarTiempoReservado); 
            }
            if(!txtTiempoReservadoDia.getText().equals("0")) {
                auxiliarTiempoReservado = Long.parseLong(txtTiempoReservadoDia.getText());
                fechaSalida = fechaSalida.plusDays(auxiliarTiempoReservado);

            }
            if(!txtTiempoReservadoMes.getText().equals("0")) {
                auxiliarTiempoReservado = Long.parseLong(txtTiempoReservadoMes.getText());
                fechaSalida = fechaSalida.plusMonths(auxiliarTiempoReservado);

            }
            
            if(txtTiempoReservadoHora.getText().equals("0") && txtTiempoReservadoDia.getText().equals("0") && txtTiempoReservadoMes.getText().equals("0") ) {
                JOptionPane.showMessageDialog(this,"Hab. "+habitacionAsignada+" necesita algun \ntiempo de reserva.");

            }
            return fechaSalida;
        } else {
            return LocalDateTime.now();
        }
    }
}
